### ISSUE TITLE
Variable collision on functions with non-local variables.  

### ISSUE THREAD

**Issue by VDFaller** [sassoftware/jsl-hamcrest#46]
# Issue
Hamcrest fails when functions have non-local variables it seems

# replicable code 

    f = function({}, 
        {dt//, h1 // it seems that any variable not local will error out, 
        },
        dt = open("$SAMPLE_DATA\Big Class.jmp");
        h1 = dt:height[1];
        return(h1);
    );
    case = uttestcase("Testy");
    uttest(case, "dt scoping", 
        	utassertthat(Expr(f()), 59)
    );

# failure
`
FAILURE  f() equal to 59 
    Actual: threw "Error: The member variable "h1" defined in class "UtEqualToNumberMatcher" cannot be accessed from the function "f". 1 time."
    Expected: equal to 59
`

**Comment by JustinChilton** [comment]
So it looks like this is a bug in JMP that causes here/global variables to be inaccessible unscoped when a method is in the call stack. 

There are a few ways of fixing this. 

1. Remove most of the evaluation outside of the text expression. This prevents the collision since the evaluation is being done outside of the assertion and matcher. This requires no changes to your existing functions, only how the functions are tested.
```jsl
f = function({}, {dt},
    dt = open("$SAMPLE_DATA\Big Class.jmp");
    h1 = dt:height[1];
    h1;
);
uttest("Testy", "dt scoping", Expr(
    result = f();
    utassertthat(Expr(result), 59);
));
```
2. Explicitly scope variables in here/global. This is mostly just a way to show the root of the problem, because it would require changes to the functions you are testing.
```jsl
f = function({}, {dt},
    dt = open("$SAMPLE_DATA\Big Class.jmp");
    ::h1 = dt:height[1];
    ::h1;
);

uttest("Testy", "dt scoping", Expr(
    utassertthat(Expr(f()), 59)
));
```
3. What we are planning to do to fix this issue is to create a new assertion function that allows you to move the evaluation to the call site instead of within the matcher. This would allow you to write something like below.
```jsl
ut assert value( f(), 59 );
```
