### ISSUE TITLE
Conditionally add functions to Scripting Index using custom functions

### ISSUE THREAD

**Issue by JustinChilton** [sassoftware/jsl-hamcrest#58]
We will need to investigate the best way to do this, because not everyone would necessarily want the functions installed. And since the functions are in globals, is there a good way for us to organize them together in the Scripting Index? And can we do this without crowding up the source code while still making it manageable to make sure each function has a definition.

**Comment by JustinChilton** [comment]
@VDFaller, was this what you had in mind for the Scripting Index?

**Comment by VDFaller** [comment]
@JustinChilton, kind of.  I was more suggesting not having them in globals but basically having a UT namespace since `new custom function` requires a namespace. So the call would be `UT:assertthat()`.  You can use "global" as the namespace but I imagine that's not intended as you can't overwrite the `add` function for instance.   I understand this is not a small change.   And since there isn't an equivalent `new custom class`, this may not be the best option currently since matchers wouldn't have equal documentation.  

I've been playing with the option of putting stuff in the scripting index or not and I've come up with a few ways. The way I saw the problem is no matter what we wanted the calls to be the same.    
# Option 1: create functions locally then just assign them in `new custom function`
```
f = function({});
if(we_want_scripting_index,
    new custom function("ut", "f", f);
, // else
  ut:f = nameexpr(f);
);
```

But this. I'm running into an issue if the function is a constructor for a class (that I can't exactly replicate easily yet).  
# Option 2: Delete and recreate the namespace
Do everything only with `new custom function`.  
Then just at the end of the script
```
if(we_dont_want_scripting_index,
    ns_copy = copy_namespace("UT"); // copies the namespace to an anonymous namespace
    delete_namespace("UT"); // deletes the ut namespace and removes any custom functions that have UT as the namespace
    copy_namespace(ns_copy, "UT"); // copies the namespace back over to UT
);
```

We could also just make a function `remove_UT` or something so that would be a one line operation.

I'm leaning toward the second one personally.
