### ISSUE TITLE
Trivial assertions result in "Expression Failure" message

### ISSUE THREAD

**Issue by dougiechong** [sassoftware/jsl-hamcrest#62]
```
ut test( "Simple Pass", "One equals one", Expr(
	ut assert that( Expr(1), ut equal to(1) );
));

ut test( "Simple Pass", "dog equals dog", Expr(
	ut assert that( Expr("dog"), ut equal to("dog") );
));
```

The trivial test cases shown above result in an "Expression Failure" message

**Comment by emccorkle** [comment]
This, unfortunately, is expected behavior and is a result of the check at [Core.jsl#L52-L66](https://github.com/sassoftware/jsl-hamcrest/blob/master/Source/Core/Core.jsl#L52-L66). This is meant to force the user to wrap their `test expr` in `Expr`. In JSL, wrapping a number or string literal in `Expr` does not change its type and it will not pass the `Is Expr` test. If we allow literals here, we will have no way to distinguish between your example above and a more complicated expression that evaluated to a number or string at the callsite. The latter could potentially throw and is what we are trying to protect against.

You can use [ut as expr](https://github.com/sassoftware/jsl-hamcrest/blob/5a0d45b6341a947056edd250c3484be18cf77b5f/Source/Core/Utils.jsl#L450-L457) or [ut assert value](https://github.com/sassoftware/jsl-hamcrest/blob/69238f025f312ac151e54305139a8c974daa56f5/Source/Core/Core.jsl#L119-L144) to work around this issue.
