### ISSUE TITLE
Clarify failure message when empty expression is evaluated with ut assert that().

### ISSUE THREAD

**Issue by himanga** [sassoftware/jsl-hamcrest#99]
In all four of the tests below an empty value is evaluated, but in the first three tests a failure message seems to indicate that the test code was written incorrectly, rather than the test failing because the function being tested didn't do what it was supposed to.

``` jsl
ut with reporter( ut streaming log reporter(), Expr( 
	ut test( "Example", "Unclear Result", Expr(
		ut assert that( .                    , 1 );
		ut assert that( Expr( . )            , 1 );
		ut assert that( if( 1==2, 1 )        , 1 );
		ut assert that( Expr( if( 1==2, 1 ) ), 1 );
	))
));
```
the resulting log messages are:
```
FAILURE  Test #1: test expr first argument to assertion is ... (Example ⮚ Unclear Result ⮚ 1) 
         Actual: was not an expression
       Expected: first argument to assertion is an expression
FAILURE  Test #2: test expr first argument to assertion is ... (Example ⮚ Unclear Result ⮚ 2) 
         Actual: was not an expression
       Expected: first argument to assertion is an expression
FAILURE  Test #3: test expr first argument to assertion is ... (Example ⮚ Unclear Result ⮚ 3) 
         Actual: was not an expression
       Expected: first argument to assertion is an expression
FAILURE  Test #4: If(1 == 2, 1) equal to 1 (Example ⮚ Unclear Result ⮚ 4) 
         Actual: was .
       Expected: equal to 1
            LRE: .
```
The last message is useful, I propose this should be the behavior anytime the first argument of ut assert that, and maybe other functions, evaluates as missing.

**Comment by JustinChilton** [comment]
Apologies for the late reply, I must not have had notifications set up correctly.

The issue here is that `.`, `Expr(.)`, and `If(1==2, 1)` are not actually expressions, since they are literals or get immediately evaluated. This means that it fails before even being sent to the matcher. However, `Expr(If(1==2, 1)` is an expression, so it gets sent to the `UtEqualToMatcher` and fails there with an appropriate message.

To get the behavior you are looking for, I would suggest `ut assert value`, which removes the requirement for an expression.

The reason it needs to be an expression is because it needs to be evaluated by the matcher. If it is not an expression, it gets evaluated before being sent to the matcher. `ut assert value` is a way to opt out of that behavior.

**Comment by himanga** [comment]
Thank you.

In hindsight I cannot think of a way to make it more clear that the user either forgot to use an Expr( or are testing something that isn't an expression.
